[FEAT] Added usage description and fzf check
fzf fuzzy finder is an extremely useful utility.

diff --git a/zet b/zet
--- a/zet
+++ b/zet
@@ -1,17 +1,33 @@
 #!/bin/sh
 
-###################################################
-#                || DISCLAIMER ||                 #
-#  This multicommand script works on hard links.  #
-#  The path of the execution relies on the name   #
-#               of the executable.                #
-#                                                 #
-#  Make sure you `ln zet [zetf, zetp zetg]` and   #
-#        have these files on the $PATH.           #
-###################################################
-
 editor="${EDITOR:-vi}"
 zettel_dir="${JOURNAL:-$HOME}/zettel"
+fuzzy="fzf"
+usage='USAGE:
+	zet [-h]
+	zetf [-h]
+	zetp [-h] [strings ...]
+	zetg [-h] [strings ...]
+
+	Manage your Zettelkasten with one shell script.
+
+
+Zet will prompt you for the name of a Zettelkasten entry.
+
+Zetf will let you browse through the existing entries with fzf.
+
+Zetp takes positional arguments or reads from STDIN and prints out
+matching Zettelkasten entry file names.
+
+Zetg takes positional arguments or reads from STDIN and prints out
+file names with contents matching one or more arguments.
+
+EXAMPLES:
+	zetp sql
+	zetg shell
+	echo "sql shell" | zetp
+	echo "shell sql" | zetg
+'
 
 create_entry () {
 	printf "Enter a name: "; read -r name
@@ -53,6 +69,11 @@ grep_links() {
 		done < "/dev/stdin"
 	fi
 }
+
+! command -v "$fuzzy" > "/dev/null" && echo "$fuzzy was not found zetf won't work." && exit 1
+
+test "$1" = "--help" -o "$1" = "-h" && echo "$usage" && exit 0
+
 test "${0##*/}" = zetp && paste_links "$@" && exit 0
 
 test "${0##*/}" = zet && create_entry
